name: "Ingress Proxy"
description: "Proxy server pro přístup k lokálním zařízením v síti s možností přepisování cest"
version: "1.0.8"
slug: "ingress-proxy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ingress: true
ingress_port: 8080
panel_icon: "mdi:router-network"
panel_title: "Ingress Proxy"
options:
  devices:
    - name: "Example Device"
      target_host: "192.168.1.100"
      target_port: 80
      path_prefix: "/device1"
      rewrite_paths: true
      custom_headers:
        - "X-Forwarded-For: $remote_addr"
      auth_required: false
      minimize_headers: false
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
  minimize_headers: false
schema:
  devices:
    - name: str
      target_host: str
      target_port: int
      path_prefix: str?
      rewrite_paths: bool?
      custom_headers:
        - str?
      auth_required: bool?
      basic_auth_user: str?
      basic_auth_pass: str?
      minimize_headers: bool?
  ssl: bool?
  certfile: str?
  keyfile: str?
  log_level: list(debug|info|warning|error)?
  minimize_headers: bool?
